name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zuneha/hello-world-spring-boot:${{ github.sha }}

    - name: Install Kyma CLI
      run: |
        curl -Lo kyma https://storage.googleapis.com/kyma-cli-stable/kyma-darwin
        chmod +x kyma
        sudo mv kyma /usr/local/bin

    - name: Deploy to Kyma
      env:
        KUBECONFIG: kubeconfig.yaml
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
        kubectl create namespace your-namespace || true
        kubectl apply -n your-namespace -f deployment.yml
